### ISSUE TITLE
User Inputs for Wing Tattering Damage Distribution

### ISSUE THREAD

**Issue by georgoff** [smitdave/MASH-Main#133]
The wing tattering damage distribution is a **beta distribution**, which requires `alpha` and `beta` parameters. Team members have discussed allowing the user to specify alternate parameters, such as `mean` and `variance`. However, it is undecided which alternate parameters to use.

Once decided, these need to be implemented in the GUI. Currently, `mean` and `variance` are being used.

**Comment by slwu89** [comment]
defunct issue.
