### ISSUE TITLE
JSON file structure changed so the old plot routines will not work 

### ISSUE THREAD

**Issue by Chipdelmal** [smitdave/MASH-Main#36]
The plots routines assumed a JSON file structure that was changed somewhere in the new implementation of the mosquito export routines (when the change between the _old repo_ and _new repo_ took place). This is a "heads up" to the fact that the routines will not work under current conditions... which makes me want to cry... like... really... I'm holding back my tears...

There's three ways to fix this:

* Correct the export routine to match the pattern we used to use in the previous implementations
* Create a parser that transforms the current JSONs into the old ones.
* Correct ALL the plot routines (PlotLy, old GUI, Mathematica debugging)

I don't particularly like either but the second one's probably the easiest. Creating a parser that takes the output and reshapes it into the old format.

*Examples:*

[JSONExamples.zip](https://github.com/smitdave/MASH-Main/files/1532285/JSONExamples.zip)

* Old

```
{
  "mosy0_1": {
    "stateH": ["M", "S", "R", "M", "S", "R", "M", "D"],
    "timeH": [0, 1.88, 2.6141, 4.1225, 4.4081, 4.4208, 5.0948, 6.8518],
    "ixH": [7, 9, 2, 2, 9, 2, 2, 9],
    "pSetH": ["l", "m", "s", "s", "m", "s", "s", "m"]
  },
  "mosy0_2": {
    "stateH": ["M", "S", "R", "M", "S", "R", "M", "S", "S", "R", "D"],
    "timeH": [0, 1.0134, 2.3703, 3.5957, 4.2056, 4.276, 6.128, 6.2672, 6.2891, 6.7466, 7.6983],
    "ixH": [6, 7, 10, 10, 10, 10, 10, 5, 10, 7, 7],
    "pSetH": ["l", "m", "s", "s", "m", "s", "s", "m", "s", "s", "s"]
  },...
}
```

* New

```
[
  {
    "ID": ["0_10_1"],
    "stateH": ["emerge", "M", "D"],
    "timeH": [0, 0, 1.2619],
    "ixH": [1, 10],
    "pSetH": ["l", "m"]
  },
  {
    "ID": ["0_4_1"],
    "stateH": ["emerge", "M", "R", "D"],
    "timeH": [0, 0, 0.6801, 0.7045],
    "ixH": [1, 9, 9],
    "pSetH": ["l", "m", "m"]
  },...
]
```

**Comment by slwu89** [comment]
🤔

**Comment by slwu89** [comment]
fixes found in `/master/MASH-dev/SeanWu/PLOTS_Bionomics.R` where `data` is read in as (examples in mbites_paper1.R):

```
  mHist = fromJSON(txt = paste0(master_dir,l,"/MOSQUITO/",hist_l),flatten = FALSE,simplifyVector=FALSE)
  
  nullIx = which(vapply(X = mHist,FUN = function(x){x$ID[[1]]},FUN.VALUE = character(1)) == "NULL")
  mHist = mHist[-nullIx]
```
